name: noteslock
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.4.0
  scoped_model: ^0.3.0
  sqflite: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_admob: 0.7.0
  path_provider: "^0.4.1"
  share: ^0.5.3
  url_launcher: 3.0.3
  
  local_auth: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpe
  assets:
    - assets/noteslockicon.png
    - assets/notesimage.jpg
    - assets/alarm.png
    - assets/atm.png
    - assets/bee.png
    - assets/calender.png
    - assets/celebrity.png
    - assets/chemistry.png
    - assets/family.png
    - assets/female.png
    - assets/fight.png
    - assets/ghost.png
    - assets/girlghost.png
    - assets/group.png
    - assets/hack.png
    - assets/joker.png
    - assets/male.png
    - assets/math.png
    - assets/peace.png
    - assets/peacock.png
    - assets/personf.png
    - assets/personm.png
    - assets/popeye.png
    - assets/spy.png
    - assets/student.png
    - assets/swan.png
    - assets/tension.png
    - assets/love.png
    - assets/god.png
    - assets/map.png
    - assets/food.png
    - assets/notes.png
    - assets/removebook.png
    - assets/books.png
    - assets/book.png
    - assets/books2.png
    - assets/key.png
    - assets/lock.png
    - assets/delete.png
    - assets/travel.png
    - assets/krishna.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BadMofo
      fonts:
        - asset: fonts/BadMofo.ttf
    - family: Celestia
      fonts:       
        - asset: fonts/Celestia.ttf
    - family: balaram_
      fonts:        
        - asset: fonts/balaram_.ttf
    - family: jandles
      fonts:        
        - asset: fonts/jandles.ttf
    - family: Spitter
      fonts:        
        - asset: fonts/Spitter.ttf
    - family: shaky
      fonts:
        - asset: fonts/shaky.ttf
    - family: CHLORINR
      fonts:      
        - asset: fonts/CHLORINR.ttf
    - family: Tr2n
      fonts:      
        - asset: fonts/Tr2n.ttf
    - family: njnaruto
      fonts:      
        - asset: fonts/njnaruto.ttf
    - family: Eutemia
      fonts: 
        - asset: fonts/Eutemia.ttf
    - family: BLKCHCRY
      fonts:      
        - asset: fonts/BLKCHCRY.ttf
    - family: MetalMacabre
      fonts:      
        - asset: fonts/MetalMacabre.ttf
    - family: TheGodfather
      fonts:      
        - asset: fonts/TheGodfather-v2.ttf
    - family: SCRIPTIN
      fonts:      
        - asset: fonts/SCRIPTIN.ttf
    - family: MANGAL
      fonts:      
        - asset: fonts/MANGAL.ttf


  # - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
